# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: keyword_spotter.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'keyword_spotter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15keyword_spotter.proto\x12\x0fkeywordspotting\"H\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x11\n\tclient_id\x18\x03 \x01(\t\"J\n\x12PredictionResponse\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32h\n\x0e\x41udioProcessor\x12V\n\x0ePredictCommand\x12\x1d.keywordspotting.AudioRequest\x1a#.keywordspotting.PredictionResponse\"\x00\x42\x34\n\x1a\x63om.miniproject.year4.grpcB\x14KeywordSpottingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyword_spotter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.miniproject.year4.grpcB\024KeywordSpottingProtoP\001'
  _globals['_AUDIOREQUEST']._serialized_start=42
  _globals['_AUDIOREQUEST']._serialized_end=114
  _globals['_PREDICTIONRESPONSE']._serialized_start=116
  _globals['_PREDICTIONRESPONSE']._serialized_end=190
  _globals['_AUDIOPROCESSOR']._serialized_start=192
  _globals['_AUDIOPROCESSOR']._serialized_end=296
# @@protoc_insertion_point(module_scope)
