# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import keyword_spotter_pb2 as keyword__spotter__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in keyword_spotter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioProcessorStub:
    """--- The Service Definition ---
    This is the actual network interface your ThreadPoolExecutor will call
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictCommand = channel.unary_unary(
                '/keywordspotting.AudioProcessor/PredictCommand',
                request_serializer=keyword__spotter__pb2.AudioRequest.SerializeToString,
                response_deserializer=keyword__spotter__pb2.PredictionResponse.FromString,
                _registered_method=True)


class AudioProcessorServicer:
    """--- The Service Definition ---
    This is the actual network interface your ThreadPoolExecutor will call
    """

    def PredictCommand(self, request, context):
        """A simple Unary RPC: Sends one audio chunk, gets one prediction back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictCommand,
                    request_deserializer=keyword__spotter__pb2.AudioRequest.FromString,
                    response_serializer=keyword__spotter__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keywordspotting.AudioProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('keywordspotting.AudioProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioProcessor:
    """--- The Service Definition ---
    This is the actual network interface your ThreadPoolExecutor will call
    """

    @staticmethod
    def PredictCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keywordspotting.AudioProcessor/PredictCommand',
            keyword__spotter__pb2.AudioRequest.SerializeToString,
            keyword__spotter__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
